/*
  PROBLEM 2: Even Fibonacci numbers

  Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
  By starting with 1 and 2, the first 10 terms will be:

  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

  By considering the terms in the Fibonacci sequence whose values do 
  not exceed four million, find the sum of the even-valued terms.

*/

// Author: Lee Allison, April 11, 2017

int p2()
{
	int sum(0);

	int f0(1), f1(1), ft(0);
	while(true)
	{
		ft = f0 + f1;

		if(ft>4e6) break;

		if(ft%2==0)
			sum += ft;

		f0 = f1;
		f1 = ft;
	}

	return sum;
}
